server:
  port: ${SERVER_PORT:4550}

spring:
  application:
    name: service-cp-crime-hearing-case-event-subscription
  jpa:
    open-in-view: false
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/appdb}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true


management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info, prometheus
